import { COLORS } from '@/constants/theme';
import { Dimensions, StyleSheet } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;

export const chatDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EBF0F6',
  },
  keyboardContainer: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#2F87F2',
  },
  headerInfo: {
    flex: 1,
    marginLeft: 14
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 1,
  },
  headerSubtitle: {
    fontSize: 10,
    color: '#CFE4FF',
    fontWeight: '500',
  },
  searchBarHeader: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  searchInput: {
    flex: 1,
    height: 36,
    color: '#FFF',
    fontSize: 16,
    paddingHorizontal: 0,
  },
  searchResultsOverlay: {
    position: 'absolute',
    top: 56, // below header
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
  },
  searchResultItem: {
    padding: 16,
    borderBottomWidth: 1,
  },
  searchResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  searchResultSender: {
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  searchResultTime: {
    fontSize: 12,
  },
  searchResultContent: {
    fontSize: 14,
  },
  searchEmptyText: {
    textAlign: 'center',
    marginTop: 40,
    fontSize: 15,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  headerIcon: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinnedBannerWrap: {
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 2,
    backgroundColor: '#2F87F2',
  },
  pinnedBanner: {
    minHeight: 34,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pinnedBannerText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#EEF3FA',
  },
  pinnedBannerAction: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinnedBannerThumb: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  messagesList: {
    paddingHorizontal: 10,
    paddingVertical: 18,
    paddingBottom: 80,
    flexGrow: 1,
    justifyContent: 'flex-end'
  },
  olderLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 28,
    paddingVertical: 4,
  },
  olderLoadingText: {
    fontSize: 11,
    fontWeight: '500',
  },
  olderLoadingPlaceholder: {
    height: 14,
  },
  messageContainer: {
    marginBottom: 2,
    width: '100%',
  },
  messageContainerHighlighted: {
    backgroundColor: 'rgba(0, 104, 255, 0.09)',
    borderRadius: 12,
    paddingHorizontal: 4,
  },
  userMessageBlock: {
    alignItems: 'flex-end',
    marginLeft: 48,
  },
  otherMessageBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginRight: 48,
  },
  otherContentBlock: {
    flex: 1,
    marginLeft: 8,
    alignItems: 'flex-start',
  },
  groupSenderName: {
    fontSize: 11,
    marginLeft: 6,
    marginBottom: 4,
    fontWeight: '500',
  },
  otherAvatarSlot: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  peerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8EDF3',
  },
  messageBubble: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 18,
    maxWidth: '85%',
    minWidth: 48,
    minHeight: 30,
    justifyContent: 'center' as const,
  },
  bubbleWrapper: {
    position: 'relative' as const,
    // reserve space at bottom for reaction badges
    paddingBottom: 10,
  },
  userBubble: {
    backgroundColor: '#D0EAFF',
    borderTopRightRadius: 6,
  },
  otherBubble: {
    borderTopLeftRadius: 6,
  },
  richTextBubbleContent: {
    alignSelf: 'stretch',
  },
  richTextContainer: {
    alignSelf: 'stretch',
  },
  richTextParagraph: {
    marginBottom: 4,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  userMessageText: {
    paddingVertical: 0,
  },
  dateSeparator: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
    gap: 6,
  },
  pinnedBannerMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateSeparatorText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#FFFFFF',
    backgroundColor: '#4A4E57',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
  },
  timestamp: {
    fontSize: 10,
    marginTop: 4,
    color: '#8D929C',
    fontWeight: '400',
  },
  timestampLeft: {
    marginLeft: 4,
    alignSelf: 'flex-start',
  },
  timestampRight: {
    marginRight: 4,
    alignSelf: 'flex-end',
  },
  recalledText: {
    fontSize: 12,
    lineHeight: 17,
    fontStyle: 'italic',
  },
  userRecalledText: {
    color: '#526377',
  },
  editedLabel: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '500',
  },
  userEditedLabel: {
    color: '#617287',
  },
  reactionRowLeft: {
    position: 'absolute' as const,
    left: 6,
    bottom: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  reactionRowRight: {
    position: 'absolute' as const,
    right: 6,
    bottom: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  reactionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reactionChipWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 5,
    paddingVertical: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reactionChipText: {
    fontSize: 12,
    color: '#2D3640',
    fontWeight: '600',
  },
  reactionTotalText: {
    fontSize: 11,
    color: '#2D3640',
    fontWeight: '700',
    paddingLeft: 1,
    paddingRight: 2,
  },
  clearButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
  },
  emptyText: {
    textAlign: 'center',
    marginTop: 40,
    fontSize: 15,
  },
  reactionViewerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  reactionViewerSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    minHeight: '52%',
    maxHeight: '80%',
    paddingTop: 8,
    overflow: 'hidden',
  },
  reactionViewerHandle: {
    width: 44,
    height: 5,
    borderRadius: 999,
    alignSelf: 'center',
    backgroundColor: '#D7DCE5',
    marginBottom: 10,
  },
  reactionViewerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
  },
  reactionViewerTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  reactionViewerTabs: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  reactionViewerTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  reactionViewerTabActive: {
    backgroundColor: 'rgba(0, 104, 255, 0.10)',
  },
  reactionViewerTabText: {
    fontSize: 13,
    fontWeight: '600',
  },
  reactionViewerList: {
    flex: 1,
  },
  reactionViewerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  reactionViewerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E8EDF3',
  },
  reactionViewerItemMain: {
    flex: 1,
    minWidth: 0,
  },
  reactionViewerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reactionViewerName: {
    fontSize: 14,
    fontWeight: '700',
    flexShrink: 1,
  },
  reactionViewerMeta: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  reactionViewerEmoji: {
    fontSize: 14,
  },
  reactionViewerCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6C7480',
  },
  inputArea: {
    flexDirection: 'column',
    alignItems: 'stretch',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    gap: 6,
    backgroundColor: '#FFFFFF',
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    backgroundColor: '#F4F7FC',
    borderWidth: 1,
    borderColor: '#DEE5EF',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  editingBannerTextWrap: {
    flex: 1,
    marginRight: 8,
  },
  editingBannerTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2A3340',
  },
  editingBannerSubtitle: {
    marginTop: 2,
    fontSize: 11,
    color: '#6C7480',
  },
  editingCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 4,
    justifyContent: 'center',
  },
  attachButton: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    borderWidth: 0,
    borderRadius: 0,
    paddingHorizontal: 2,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: '500',
    backgroundColor: 'transparent',
  },
  bottomActionButton: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  actionSheet: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 10,
    paddingTop: 16,
    paddingBottom: 20,
  },
  emojiRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 6,
  },
  emojiButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: '#F4F6FA',
  },
  emojiButtonText: {
    fontSize: 28,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 4,
  },
  actionGridItem: {
    width: '25%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  actionGridIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  actionGridLabel: {
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  pinnedSheet: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '70%',
    paddingTop: 12,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  pinnedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  pinnedTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  pinnedList: {
    maxHeight: 420,
  },
  pinnedEmpty: {
    paddingVertical: 20,
    textAlign: 'center',
    fontSize: 13,
  },
  pinnedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    gap: 8,
  },
  pinnedItemMain: {
    flex: 1,
    gap: 2,
  },
  pinnedContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pinnedSender: {
    fontSize: 12,
    fontWeight: '700',
  },
  pinnedContent: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
  },
  pinnedItemThumb: {
    width: 32,
    height: 32,
    borderRadius: 4,
    backgroundColor: '#E6EBF2',
  },
  unpinButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ── Media message styles ──────────────────
  mediaBubble: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: 'transparent',
    borderRadius: 6,
    overflow: 'hidden' as const,
  },
  mediaImage: {
    width: 220,
    height: 220,
    borderRadius: 6,
    backgroundColor: '#000000',
  },
  mediaUploadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  mediaUploadingText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  videoContainer: {
    width: 220,
    height: 160,
    borderRadius: 6,
    backgroundColor: '#1A1A2E',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden' as const,
  },
  videoThumbnailImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  videoPlayOverlay: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoDurationBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  videoDurationText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  fileNameText: {
    fontSize: 11,
    marginTop: 2,
  },
  fileBubbleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 200,
  },
  fileIconWrap: {
    width: 44,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#EBF0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileExtLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  fileInfoWrap: {
    flex: 1,
    gap: 2,
  },
  fileNameMainText: {
    fontSize: 13,
    fontWeight: '600',
  },
  fileSizeText: {
    fontSize: 11,
  },
  // ── Media preview banner ──────────────────
  mediaPreviewBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#F4F7FC',
    borderWidth: 1,
    borderColor: '#DEE5EF',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 10,
  },
  mediaPreviewThumb: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#E8EDF3',
  },
  mediaPreviewFileIcon: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#EBF0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaPreviewInfo: {
    flex: 1,
    gap: 2,
  },
  mediaPreviewName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2A3340',
  },
  mediaPreviewSize: {
    fontSize: 11,
    color: '#6C7480',
  },
  mediaPreviewClose: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadProgressBar: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#DEE5EF',
    marginTop: 4,
    overflow: 'hidden' as const,
  },
  uploadProgressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: COLORS.primary,
  },
  // ── Multi-image preview ──────────────────
  multiImagePreviewContainer: {
    backgroundColor: '#F4F7FC',
    borderTopWidth: 1,
    borderTopColor: '#DEE5EF',
    paddingTop: 8,
    paddingBottom: 4,
    paddingHorizontal: 8,
  },
  multiImageScroll: {
    maxHeight: 90,
  },
  multiImageScrollContent: {
    gap: 6,
    paddingRight: 4,
  },
  multiImageThumbWrap: {
    width: 72,
    height: 72,
    borderRadius: 8,
    overflow: 'hidden' as const,
    backgroundColor: '#E0E6EF',
  },
  multiImageThumb: {
    width: 72,
    height: 72,
  },
  multiImageUploadOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  multiImageUploadPct: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  multiImageDoneOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,168,80,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  multiImageRemoveBtn: {
    position: 'absolute',
    top: 2,
    right: 2,
  },
  multiImageFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    paddingHorizontal: 2,
  },
  multiImageCount: {
    fontSize: 12,
    color: '#6C7480',
  },
  multiImageCancelText: {
    fontSize: 12,
    color: '#F04343',
    fontWeight: '600',
  },
  // ── Attach menu ──────────────────
  attachMenuTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  // ── Reply bar ─────────────────────
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    gap: 8,
    minHeight: 52,
  },
  replyBarAccent: {
    width: 3,
    height: 36,
    borderRadius: 2,
    backgroundColor: '#0068FF',
    flexShrink: 0,
  },
  replyBarContent: {
    flex: 1,
    gap: 2,
  },
  replyBarSender: {
    fontSize: 12,
    fontWeight: '700',
  },
  replyBarSnippet: {
    fontSize: 12,
  },
  replyBarDismiss: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ── Reply snippet inside bubble ───
  replySnippetBlock: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#0068FF',
    maxWidth: '100%',
  },
  replySnippetBlockUser: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  replySnippetBlockOther: {
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  replySnippetSender: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  replySnippetText: {
    fontSize: 12,
  },
  // ── Forwarded banner ──────────────
  forwardedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  forwardedBannerText: {
    fontSize: 11,
    fontStyle: 'italic',
  },
  // ── Contact card ──────────────────
  contactCard: {
    borderRadius: 12,
    overflow: 'hidden',
    minWidth: 220,
    backgroundColor: '#F4F7FC',
    borderWidth: 1,
    borderColor: '#DEE5EF',
  },
  contactCardUser: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.3)',
  },
  contactCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 10,
  },
  contactCardAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactCardAvatarImg: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  contactCardAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  contactCardInfo: {
    flex: 1,
    gap: 2,
  },
  contactCardName: {
    fontSize: 14,
    fontWeight: '700',
  },
  contactCardPhone: {
    fontSize: 12,
  },
  contactCardDivider: {
    height: 1,
    marginHorizontal: 0,
  },
  contactCardBtn: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  contactCardBtnText: {
    fontSize: 14,
    fontWeight: '600',
  },
  // ── Forward / Share Contact modals ─
  fwdSheet: {
    maxHeight: '80%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 16,
  },
  fwdHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  fwdTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  fwdPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
  },
  fwdPreviewText: {
    fontSize: 13,
    flex: 1,
  },
  fwdPreviewImageWrap: {
    flexDirection: 'row',
    gap: 4,
    flexShrink: 0,
  },
  fwdPreviewImageThumb: {
    width: 36,
    height: 36,
    borderRadius: 6,
  },
  fwdPreviewVideoWrap: {
    width: 44,
    height: 36,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#1F2937',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  fwdPreviewVideoThumb: {
    width: '100%',
    height: '100%',
  },
  fwdPreviewVideoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fwdPreviewFileIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: 'rgba(0,104,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  fwdSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
  },
  fwdSearchInput: {
    flex: 1,
    fontSize: 14,
    height: 36,
    padding: 0,
  },
  fwdList: {
    maxHeight: 320,
    paddingHorizontal: 16,
  },
  fwdItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
  },
  fwdItemAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0068FF',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  fwdSpecialAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fwdAiAvatar: {
    backgroundColor: '#0068FF',
  },
  fwdCloudAvatar: {
    backgroundColor: '#00A86B',
  },
  fwdItemAvatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  fwdItemAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  fwdItemName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
  },
  fwdCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  fwdCheckboxSelected: {
    backgroundColor: '#0068FF',
  },
  fwdFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    marginTop: 4,
  },
  fwdSelectedCount: {
    fontSize: 13,
  },
  fwdSendBtn: {
    backgroundColor: '#0068FF',
    paddingHorizontal: 22,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 80,
    alignItems: 'center',
  },
  fwdSendBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  // Share contact toggle
  scToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  scToggleLabel: {
    fontSize: 14,
  },
  scToggle: {
    width: 40,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    position: 'relative',
  },
  scToggleThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
  },
  // ── Fullscreen image preview ──────
  fullscreenImageBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenImage: {
    width: '100%',
    height: '80%',
  },
  fullscreenImageClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  fullscreenImageDownload: {
    position: 'absolute',
    bottom: 50,
    padding: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 24,
  },
  fullscreenVideo: {
    width: '100%',
    height: '75%',
  },
  // ── Emoji picker ──────────────────
  emojiPickerPanel: {
    height: 240,
    borderTopWidth: 1,
    borderTopColor: '#E5E9EF',
    backgroundColor: '#FFFFFF',
  },
  emojiPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 8,
  },
  emojiPickerItem: {
    width: '12.5%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emojiPickerText: {
    fontSize: 26,
  },
  // ── Voice message bubble ──────────
  voiceBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 2,
    minWidth: 180,
  },
  voiceWaveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  voiceBar: {
    width: 3,
    borderRadius: 2,
    backgroundColor: '#9EBCD8',
  },
  voiceDurationText: {
    fontSize: 12,
    fontWeight: '500',
    minWidth: 32,
    textAlign: 'right',
  },
  // ── Recording UI ──────────────────
  recordingBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
  },
  recordingIndicator: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FF3B30',
  },
  recordingTimeText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FF3B30',
  },
  recordingLabel: {
    fontSize: 12,
    color: '#7B808A',
  },
  recordingCancelBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingSendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Info Panel ────────────────────────────────────────────────────────────
  infoPanelContainer: {
    flex: 1,
  },
  infoPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  infoPanelTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  infoPanelScroll: {
    flex: 1,
  },
  infoPanelProfile: {
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  infoPanelAiAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#06B6D4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoPanelCloudAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#0068FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoPanelAvatarImg: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginBottom: 12,
  },
  infoPanelDefaultAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#4A90D9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoPanelDefaultAvatarText: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  infoPanelName: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  infoPanelSubName: {
    fontSize: 13,
    textAlign: 'center',
  },
  infoPanelAvatarWrap: {
    position: 'relative',
  },
  infoPanelAvatarCameraBadge: {
    position: 'absolute',
    right: -3,
    bottom: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  infoPanelNameRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoPanelNameEditBtn: {
    marginLeft: 8,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoNameModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  infoNameModalCard: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
  },
  infoNameModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  infoNameModalInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  infoNameModalActions: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  infoNameModalBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  infoNameModalBtnText: {
    fontSize: 13,
    fontWeight: '600',
  },
  infoNameModalBtnPrimary: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: COLORS.primary,
  },
  infoNameModalBtnPrimaryDisabled: {
    backgroundColor: '#9DBEF9',
  },
  infoNameModalBtnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  addMemberModalContainer: {
    flex: 1,
  },
  addMemberModalHeader: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 10,
  },
  addMemberModalBackBtn: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberModalHeaderCenter: {
    flex: 1,
    marginLeft: 4,
  },
  addMemberModalTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  addMemberModalSubtitle: {
    marginTop: 2,
    fontSize: 11,
  },
  addMemberModalActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  addMemberModalActionBtnDisabled: {
    backgroundColor: '#9DBEF9',
  },
  addMemberModalActionBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginTop: 12,
    marginBottom: 8,
  },
  searchIcon: {
    marginRight: 6,
  },
  addMemberSearchInput: {
    flex: 1,
    fontSize: 13,
    paddingVertical: 12,
  },
  addMemberListWrap: {
    flex: 1,
  },
  addMemberListContent: {
    paddingBottom: 20,
  },
  addMemberLetterRow: {
    paddingHorizontal: 16,
    paddingVertical: 3,
    borderTopWidth: StyleSheet.hairlineWidth,
    backgroundColor: '#F1F2F4',
  },
  addMemberLetterText: {
    fontSize: 13,
    fontWeight: '700',
  },
  addMemberFriendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  addMemberAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberAvatarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  addMemberFriendInfo: {
    flex: 1,
    marginLeft: 12,
  },
  addMemberFriendName: {
    fontSize: 14,
    fontWeight: '500',
  },
  addMemberFriendSub: {
    marginTop: 2,
    fontSize: 11,
  },
  addMemberCheckCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#999FA8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberCheckCircleSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  addMemberEmptyWrap: {
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberEmptyText: {
    fontSize: 12,
  },
  infoPanelQuickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
    marginTop: 18,
    paddingHorizontal: 8,
  },
  infoPanelQuickAction: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  infoPanelQuickActionIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  infoPanelQuickActionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  infoPanelSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  infoPanelSectionToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  infoPanelSectionToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoPanelSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  infoPanelCapItem: {
    fontSize: 13,
    marginTop: 4,
    lineHeight: 20,
  },
  infoPanelDangerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 9,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(240,67,67,0.08)',
    borderRadius: 8,
    justifyContent: 'center',
  },
  infoPanelDangerBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#F04343',
  },
  infoPanelStorageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  infoPanelStorageUsed: {
    fontSize: 12,
  },
  infoPanelStorageBar: {
    flexDirection: 'row',
    height: 10,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    marginBottom: 10,
  },
  infoPanelStorageSegment: {
    height: '100%',
  },
  infoPanelStorageLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoPanelLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  infoPanelLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  infoPanelLegendText: {
    fontSize: 11,
  },
  infoPanelMemberList: {
    marginTop: 8,
  },
  infoPanelAddMemberBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(0,104,255,0.08)',
    borderRadius: 8,
    justifyContent: 'center',
    marginBottom: 8,
  },
  infoPanelAddMemberBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0068FF',
  },
  infoPanelAddPanel: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  infoPanelAddPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoPanelAddPanelTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  infoPanelFriendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 7,
  },
  infoPanelSmallAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  infoPanelMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 10,
    position: 'relative',
  },
  infoPanelMemberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  infoPanelMemberInfo: {
    flex: 1,
  },
  infoPanelMemberName: {
    fontSize: 13,
    fontWeight: '600',
  },
  infoPanelRoleBadgeAdmin: {
    fontSize: 10,
    fontWeight: '700',
    color: '#F97316',
    marginTop: 2,
  },
  infoPanelRoleBadgeDeputy: {
    fontSize: 10,
    fontWeight: '700',
    color: '#3B82F6',
    marginTop: 2,
  },
  infoPanelMemberMenuBtn: {
    padding: 6,
  },
  infoPanelMemberMenu: {
    position: 'absolute',
    right: 0,
    top: 36,
    zIndex: 10,
    borderWidth: 1,
    borderRadius: 10,
    minWidth: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  infoPanelMemberMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  infoPanelMemberMenuItemText: {
    fontSize: 13,
    fontWeight: '500',
  },
  infoPanelTransferBox: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
  },
  infoPanelEmpty: {
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: 12,
    opacity: 0.6,
  },
  infoPanelPinnedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
  },
  infoPanelPinnedIndex: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,104,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoPanelPinnedIndexText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#0068FF',
  },
  infoPanelPinnedContent: {
    flex: 1,
  },
  infoPanelPinnedSender: {
    fontSize: 12,
    fontWeight: '600',
  },
  infoPanelPinnedText: {
    fontSize: 13,
    marginTop: 2,
    flex: 1,
  },
  infoPanelPinnedPreviewRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoPanelPinnedThumb: {
    width: 36,
    height: 36,
    borderRadius: 6,
    flexShrink: 0,
  },
  infoPanelMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    marginTop: 8,
  },
  infoPanelMediaGridHeader: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoPanelMediaGridHint: {
    fontSize: 12,
    fontWeight: '500',
  },
  infoPanelMediaExpandBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  infoPanelMediaExpandBtnText: {
    color: '#0068FF',
    fontSize: 12,
    fontWeight: '700',
  },
  infoPanelMediaThumb: {
    width: '23%',
    aspectRatio: 1,
    borderRadius: 6,
    overflow: 'hidden',
  },
  infoPanelMediaThumbImg: {
    width: '100%',
    height: '100%',
  },
  infoPanelMediaPlayOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.26)',
  },
  infoMediaGalleryBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,1)',
  },
  infoMediaGalleryTopBar: {
    position: 'absolute',
    top: 54,
    left: 16,
    right: 16,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoMediaGalleryCloseText: {
    color: '#FFFFFF',
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '700',
  },
  infoMediaGalleryItem: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoMediaGalleryVideoWrap: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  infoMediaGalleryImage: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  infoMediaGalleryVideo: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  infoMediaGalleryVideoLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  infoMediaGalleryVideoPosterWrap: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoMediaGalleryVideoPlaceholder: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    backgroundColor: '#0F0F0F',
  },
  infoMediaGalleryVideoPlayButton: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  infoMediaGalleryVideoPlayButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  infoMediaActionSheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 92,
    paddingRight: 16,
  },
  infoMediaActionSheet: {
    width: 210,
    borderRadius: 10,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  infoMediaActionSheetItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  infoMediaActionSheetItemText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  globalBusyOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  globalBusyCard: {
    minWidth: 190,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.75)',
    alignItems: 'center',
    gap: 10,
  },
  globalProgressTrack: {
    width: 180,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  globalProgressFill: {
    height: '100%',
    backgroundColor: '#4DA3FF',
  },
  globalBusyPercent: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  globalBusyText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '500',
  },
  infoMediaBrowserContainer: {
    flex: 1,
    backgroundColor: '#0B0D11',
  },
  infoMediaBrowserHeader: {
    height: 56,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  infoMediaBrowserTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  infoMediaBrowserFilterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
  },
  infoMediaBrowserFilterBtn: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  infoMediaBrowserFilterBtnActive: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.32)',
  },
  infoMediaBrowserFilterText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    fontWeight: '600',
  },
  infoMediaBrowserFilterTextActive: {
    color: '#FFFFFF',
  },
  infoMediaBrowserGrid: {
    paddingHorizontal: 4,
    paddingBottom: 20,
  },
  infoMediaBrowserRow: {
    gap: 4,
    marginBottom: 4,
  },
  infoMediaBrowserThumb: {
    flex: 1,
    aspectRatio: 1,
    backgroundColor: '#12161E',
    borderRadius: 4,
    overflow: 'hidden',
  },
  infoMediaBrowserThumbImage: {
    width: '100%',
    height: '100%',
  },
  infoMediaBrowserThumbOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.22)',
  },
  infoMediaBrowserEmpty: {
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    marginTop: 24,
    fontSize: 13,
  },
  infoPanelFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
  },
  infoPanelFileIcon: {
    width: 40,
    height: 40,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoPanelFileExt: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  infoPanelFileInfo: {
    flex: 1,
  },
  infoPanelFileName: {
    fontSize: 13,
    fontWeight: '500',
  },
  infoPanelFileSize: {
    fontSize: 11,
    marginTop: 2,
  },
});






